/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_umayahara_example_bitmap_plasma_PlasmaView */
#include "comUtil.h"
#ifndef _Included_jp_umayahara_example_bitmap_plasma_PlasmaView
#define _Included_jp_umayahara_example_bitmap_plasma_PlasmaView
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     jp_umayahara_example_bitmap_plasma_PlasmaView
 * Method:    renderPlasma
 * Signature: (JLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_jp_umayahara_example_bitmap_1plasma_PlasmaView_renderPlasma
  (JNIEnv *, jclass, jlong, jobject);



#ifdef __cplusplus
}
#endif

#endif
