/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_umayahara_ndksample_MainActivity */

#ifndef _Included_jp_umayahara_ndksample_MainActivity
#define _Included_jp_umayahara_ndksample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_umayahara_ndksample_MainActivity
 * Method:    msgFromNDK
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_umayahara_ndksample_MainActivity_msgFromNDK
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
